In [1]:



from sklearn.datasets import fetch_openml
#load mice protein dataset from OpenML
mice = fetch_openml(name='miceprotein', version=4, as_frame=True)
list(mice.frame.columns)
#print(mice.details)
#mice.frame.describe()


# Import required libraries
import numpy as np
import sklearn
from sklearn.neural_network import MLPClassifier


# Import model to divide data into training and testing sets
from sklearn.model_selection import train_test_split


target_column = ['class']
#derive the list of predictor column id's
predictors = list(set(list(mice.frame.columns))-set(target_column))
#standardize the predictors by diividing by the maximum
mice.frame[predictors] = mice.frame[predictors]/mice.frame[predictors].max()
#provide summary statistics for the dataframe
mice.frame.describe().transpose()

#Get rid of any rown with NA's
mice.frame = mice.frame.dropna()

#the input data
X = mice.frame[predictors].values
#the output data
y = mice.frame[target_column].values

#we encode target classes from strings to numbers as neural networks cannot require all numerical inputs and outputs
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

#divide data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
print(X_train.shape); print(X_test.shape)

#impor the neural network (aka multi-layer-perceptron library)
from sklearn.neural_network import MLPClassifier

#The network architecture will consist of 1 input layer that has as many input nodes as columns-1, 3 hidden layers of 20 nodes each,
# and an output layer with a node for each of the categories--and the network will choose the one with the highest score
#mlp = MLPClassifier(hidden_layer_sizes=(15,15,15), activation='relu', solver='adam', max_iter=2000)
mlp = MLPClassifier(hidden_layer_sizes=(20,20,20), activation='relu', solver='adam', max_iter=5000)
#we train the network
mlp.fit(X_train,y_train)

#We predict the training set
predict_train = mlp.predict(X_train)
#we predict the test set
predict_test = mlp.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print('Training accuracy')
#we report the confusion matrix for the training set
print(confusion_matrix(y_train,predict_train))
#we report various accuracy statistics for the training set
print(classification_report(y_train,predict_train))

print('Testing accuracy')
#we report the confusion matrix for the test set
print(confusion_matrix(y_test,predict_test))
#we report various accuracy statistics for the test set
print(classification_report(y_test,predict_test))

#Now rerun but above change the network architecture to
#mlp = MLPClassifier(hidden_layer_sizes=(20,20,20), activation='relu', solver='adam', max_iter=5000)


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(386, 77)
(166, 77)
Training accuracy
[[35  0  0  0  0  0  0  0]
 [ 0 54  0  0  0  0  0  0]
 [ 0  0 43  0  0  0  0  0]
 [ 0  0  0 54  0  0  0  0]
 [ 1  0  0  0 59  0  0  0]
 [ 0  0  0  0  0 51  0  0]
 [ 0  0  0  0  0  0 43  0]
 [ 0  0  0  0  0  0  0 46]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.99        35
           1       1.00      1.00      1.00        54
           2       1.00      1.00      1.00        43
           3       1.00      1.00      1.00        54
           4       1.00      0.98      0.99        60
           5       1.00      1.00      1.00        51
           6       1.00      1.00      1.00        43
           7       1.00      1.00      1.00        46

    accuracy                           1.00       386
   macro avg       1.00      1.00      1.00       386
weighted avg       1.00      1.00      1.00       386

Testing accuracy
[[10  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0 

In [ ]:
print(mice.frame.head())

    DYRK1A_N   ITSN1_N    BDNF_N     NR1_N    NR2A_N    pAKT_N   pBRAF_N  \
75  0.258222  0.318403  0.816361  0.777465  0.609248  0.384332   0.55711   
76  0.244988  0.323505  0.781607  0.761801  0.612335  0.414495  0.528993   
77  0.253311  0.327696    0.8057  0.789898  0.630803   0.38733  0.546451   
78  0.229225  0.290237  0.700673   0.69855  0.557321  0.381954  0.508387   
79  0.215606  0.291208  0.704101  0.701107  0.558276  0.390551  0.522514   

   pCAMKII_N   pCREB_N    pELK_N  ...     BAD_N    BCL2_N     pS6_N   pCFOS_N  \
75  0.499471  0.781338  0.272613  ...  0.493065   0.43183  0.831513  0.504282   
76  0.488774  0.721737  0.256022  ...  0.474396  0.465026  0.875651  0.557771   
77  0.511054  0.725885  0.284906  ...  0.504664  0.498121  0.849169   0.57566   
78  0.506229  0.633974   0.24626  ...  0.473862  0.410396  0.749505  0.472811   
79  0.518748  0.634446  0.250536  ...  0.472874  0.431544  0.810313  0.555951   

       SYP_N H3AcK18_N    EGR1_N  H3MeK4_N    CaNA_N   c

In [ ]:
print(mice.frame['class'].unique())

['c-CS-m', 'c-SC-m', 'c-CS-s', 'c-SC-s', 't-CS-m', 't-SC-m', 't-CS-s', 't-SC-s']
Categories (8, object): ['c-CS-m', 'c-CS-s', 'c-SC-m', 'c-SC-s', 't-CS-m', 't-CS-s', 't-SC-m',
                         't-SC-s']


In [ ]:
print("Unique classes:", mice.frame['class'].unique())


Unique classes: ['c-CS-m', 'c-SC-m', 'c-CS-s', 'c-SC-s', 't-CS-m', 't-SC-m', 't-CS-s', 't-SC-s']
Categories (8, object): ['c-CS-m', 'c-CS-s', 'c-SC-m', 'c-SC-s', 't-CS-m', 't-CS-s', 't-SC-m',
                         't-SC-s']
